### ISSUE TITLE
[BUG] Bungeecord /lay crash

### ISSUE THREAD

**Issue by Verdux** [armagidon-exception/PosePlugin#26]
**Describe the bug**
Everyone gets kicked off the server when a player runs the /lay command

**To Reproduce**
1. Have bungeecord server
2. Be on any sub server with poseplugin installed
3. Use /lay command
4. See error in bungeecord logs

**Expected behavior**
Not to kick all players, lay on floor like a champ

**Plugin version:**
2.0.0.1-experimental
Paper: 1.16.3 #253

**Plugins list:**
 - WorldEdit
 - PermissionsEx
 - [screenshoot]

**Console log**
https://pastebin.com/ME4DRsnn

**Comment by armagidon-exception** [comment]
I installed BungeeCord but bug isn't showing.

**Comment by Verdux** [comment]
Perhaps it's specific to one of my plugins also using the scoreboard. Here's list of my bungeecord plugins

advancedban
bungeealiases
bungeecontrol
bungeeguard
commandsync
Luckperms
maintenance
RedirectPlus
Serverlistplus
TAB (My main suspect)
Eglow tabexpansion
Nuvotifier

**Comment by armagidon-exception** [comment]
Downloaded all your plugins, bug still isn't showing. Maybe it's not because of proxy, but some plugin does it.

**Comment by Verdux** [comment]
Found the culprit, it's when using Eglow that this error happens when using /lay https://www.spigotmc.org/resources/eglow-1-9-4-1-16-4-glow-cosmetic-respects-eula-mysql.63295/

**Comment by armagidon-exception** [comment]
i found out what causes this, on your server(not bungee) there's a plugin which creating scoreboard team which already exists, so that's why it crashes.

**Comment by Verdux** [comment]
Yeah, as my reply above says. It's when I have eGlow installed on my Paper server.

**Comment by ghost** [comment]
Working on it

Fixed with latest eGlow build (Think another plugin is creating the same teamname as eGlow so changed the teamname)
BTW I saw you had TAB as your main suspect but TAB removes the player team before creating it to prevent this sort of error
