### ISSUE TITLE
[BUG] Visible armour with /lay

### ISSUE THREAD

**Issue by Verdux** [armagidon-exception/PosePlugin#29]
**Describe the bug**
The armour the player is wearing isn't turned invisible for themselves when they use /lay

**To Reproduce**
1. Equip any armour
2. Use /lay
3. Go into f5

**Expected behavior**
Armour should be invisible to all

**Screenshots**
https://i.gyazo.com/2fa6a1dd932cf08039e0e1222b60a9ca.gif

**Plugin version:**
2.0.0.1-experimental

**Comment by armagidon-exception** [comment]
are you using resource pack and optifine with custom item model support?

**Comment by Verdux** [comment]
I have Optifine and default texture pack. I had "custom entity models" enabled in settings but I just disabled that and still get the issue.

**Comment by armagidon-exception** [comment]
You have to use PosePluginItems resource pack

**Comment by Verdux** [comment]
Lay wasn't listed under the experimental options that require the resource pack. My experimental mode is disabled.

**Comment by armagidon-exception** [comment]
![image](https://user-images.githubusercontent.com/42355119/99882420-76052380-2c31-11eb-858e-b2f355fbce57.png)
i dont think so.
