### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by wiselder** [armagidon-exception/PosePlugin#31]
After the /lay commands, the plugin hides the players nicknames, and then shows them. 

It's okay, but on my server, using another plugin, all players nicknames are hidden by default, and everything breaks because of your command /lay. 

Can you somehow solve this problem at least using the configuration?

**Comment by Disguys** [comment]
You can install our special plugin that hides the nicknames of all players on the discord server StumpStudio. to do this, enter the command ?fixnametags in the #bot-spam channel, after that, your problem should disappear.
Link - https://discord.io/stumpstudio
