### ISSUE TITLE
[BUG] Item Duplication Glitch with Shulker Backpack plugins

### ISSUE THREAD

**Issue by CurryPotato69** [armagidon-exception/PosePlugin#38]
When the Player put things inside of the shulker backpack and then lay on the ground. He or she can take the items out of the shulker box and then stand up, get things in the shulker recovered like it was before he or she laid down.

Here is the Shulker Backpack plugin. 
https://www.spigotmc.org/resources/shulkerbox-backpacks-1-11-1-16-x.61073/

Is there a way to fix this? Somehow when people use Commanditem to allow quick use of EnderChest, the same problem happened again.

**Comment by armagidon-exception** [comment]
Maybe it's the backpack's bug? There's nothing in my plugin that restores items.

**Comment by CurryPotato69** [comment]
okay got it, i will ask the developer of that shulker pack plugin. Thank you.
