### ISSUE TITLE
the /crawl command is not working at all

### ISSUE THREAD

**Issue by anthony114669** [armagidon-exception/PosePlugin#48]
i want to report that the /crawl command is not working at all and i have everything set up correctly, aswell its keeping saying there is an update available when we have the latest one. thanks in advance is a great plugin!

**Comment by armagidon-exception** [comment]
Try recreating config file and enable swim in it.

**Comment by anthony114669** [comment]
> Try recreating config file and enable swim in it.

I did it but still not working :(

**Comment by nikitushu2** [comment]
> 
> 
> > Try recreating config file and enable swim in it.
> 
> I did it but still not working :(

Try these jars instead, and please, report if you can crawl under blocks.

Main jar: [https://ufile.io/u0o4w03p](https://ufile.io/u0o4w03p)
API: [https://ufile.io/vt6jqav7](https://ufile.io/vt6jqav7)

**Comment by anthony114669** [comment]
> > > Try recreating config file and enable swim in it.
> > 
> > 
> > I did it but still not working :(
> 
> Try these jars instead, and please, report if you can crawl under blocks.
> 
> Main jar: https://ufile.io/u0o4w03p
> API: https://ufile.io/vt6jqav7

Ok now seems to be working fine thanks just the only thing its I cannot pass thru 1 block high areas I'm assuming that's normal

**Comment by nikitushu2** [comment]
> 
> 
> > > > Try recreating config file and enable swim in it.
> > > 
> > > 
> > > I did it but still not working :(
> > 
> > 
> > Try these jars instead, and please, report if you can crawl under blocks.
> > Main jar: https://ufile.io/u0o4w03p
> > API: https://ufile.io/vt6jqav7
> 
> Ok now seems to be working fine thanks just the only thing its I cannot pass thru 1 block high areas I'm assuming that's normal

Not really, I have the same problem. I let the developer know
