### ISSUE TITLE
Damage Bug

### ISSUE THREAD

**Issue by Birsenberg** [armagidon-exception/PosePlugin#5]
1.pre-2 1.7.3
2.https://hastebin.com/eyinosewow.md 
3.The main ones are seen in the logs.
4.Damage is not applied when the player is lying.
5.Shttps://youtu.be/bWeSIKB9EPE

**Comment by Disguys** [comment]
please, install PosePlugin version pre-4 1.7.3, there are many bugs fixes with the damage in the /lay command
