### ISSUE TITLE
[Bug] Falldamage absoption

### ISSUE THREAD

**Issue by JaHollTV** [armagidon-exception/PosePlugin#7]
[Bug] Falldamage absoption
When you fall and type /sit over the ground you get no falldamage

**Comment by armagidon-exception** [comment]
Video, screens, logs?

**Comment by armagidon-exception** [comment]
I even made post how to fill issue form. Why nobody is reading?

**Comment by JaHollTV** [comment]
You can set text which is in an new issue so everybody kows what you need.
But actually here are no logs or errors. just jump from a tower and type /sit close to the ground. You will get no falldamage and sit(i was sitting 1 block over the ground)
