### ISSUE TITLE
[BUG] Point Right & Left - & rotation problem

### ISSUE THREAD

**Issue by JaHollTV** [armagidon-exception/PosePlugin#8]
**Describe the bug**
/point right & /point left looks like the same.
When you are in /point right animation and turn enough, then you can come into the point left animation. And the other way round.

**To Reproduce**
1. Type /point right'
2. Type /point off'
3. /type /point left'
=> No errors in console or somewhere.
=> Booth looks the same
4. /point off

5. /point right
5.1 Rotate now --> you will see that the right arm is going back and the left arm is goint forward.
So even you are in the /point right animation it switches to point right

**Expected behavior**
No matter what i do left arm should be in front by /point left and right arm by /point right

**Screenshots**
/point right
![PosePlugin_Point_Right](https://user-images.githubusercontent.com/48917504/90220933-7b202e80-de09-11ea-8ff4-091fdf16eef2.PNG)
/point left
![PosePlugin_Point_Left](https://user-images.githubusercontent.com/48917504/90220940-7d828880-de09-11ea-80f9-f926a70a807e.PNG)
Rotating:
![PosePlugin_Point_Right_and_Left](https://user-images.githubusercontent.com/48917504/90220943-7eb3b580-de09-11ea-8fa1-d747cc1633a7.PNG)

**Server version**
Paper(Spigot) 1.16.1

**Plugin version:**
poseplugin-experimental-1.8-pre-3b1

**Plugins list:**
 - 70 Plugins i want to share all of them cause of some guys building the same Server concept.
-> Discord JaHoll - i can send you if you need

**Console log**
Sadly nothing.

**Additional context**
It has time to be fixed. If it not possible then maybe switch back to one /point :)

**Comment by armagidon-exception** [comment]
It's alright, nothing to fix, it's just how minecraft works.
